{
  "id": "6YYykuhR0w8V",
  "allowLateSubmission": false,
  "allowScoreDrop": true,
  "beginDate": null,
  "categoryID": "p_-6StWVifHC",
  "courseID": "Mc4Brhlpuqwh",
  "description": "",
  "displayOrder": 10,
  "displayOrderCalendar": 999,
  "dueDate": 1455865140,
  "extraCredit": false,
  "graded": true,
  "gradingScale": null,
  "includeScoreInFinalGrade": true,
  "minScore": 0,
  "name": "HW 11",
  "onlineSubmission": "none",
  "passScoreRequired": false,
  "passingScore": 70,
  "points": 11,
  "rubric": null,
  "scoreEntry": "points",
  "scoreVisibleDate": null,
  "type": "assignment",
  "typeID": null,
  "url": "JJaE",
  "visibleDate": null,
  "weight": 25
}