[
  {
    "id": "0_IchiuRTzUE",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "T0LTPISJ6ZgW",
    "courseID": "5wyigGxZA8uJ",
    "description": "<p>Grade for reading selections of The Mythical Man-Month.</p>\n",
    "displayOrder": 2,
    "displayOrderCalendar": 999,
    "dueDate": 1459375200,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Read Mythical Man-Month",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "ETBR",
    "visibleDate": null,
    "weight": 3
  },
  {
    "id": "BGa8FTgR4Gnp",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "T0LTPISJ6ZgW",
    "courseID": "5wyigGxZA8uJ",
    "description": "<p>Grade for reading all of Peopleware.</p>\n",
    "displayOrder": 1,
    "displayOrderCalendar": 999,
    "dueDate": 1454540400,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Read Peopleware",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "p2qL",
    "visibleDate": null,
    "weight": 3
  },
  {
    "id": "BHdMWXI9b70L",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "MHDwlFKDHEaA",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 1,
    "displayOrderCalendar": 999,
    "dueDate": 1453618740,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#2 Team Deliverable: Organization Chart",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "ti0j",
    "visibleDate": null,
    "weight": 1
  },
  {
    "id": "KN7lyVw0anWe",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "MHDwlFKDHEaA",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 0,
    "displayOrderCalendar": 999,
    "dueDate": 1453013940,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#1 Team Deliverable: Publically Accessible Project Wiki",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "N_2i",
    "visibleDate": null,
    "weight": 0.5
  },
  {
    "id": "RLfvUrN95uos",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "T0LTPISJ6ZgW",
    "courseID": "5wyigGxZA8uJ",
    "description": "<p>Grade for reading all of Dynamics of Software Development.</p>\n",
    "displayOrder": 3,
    "displayOrderCalendar": 999,
    "dueDate": 1459980000,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Read Dynamics of Software Development",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "OXQb",
    "visibleDate": null,
    "weight": 3
  },
  {
    "id": "SWRp9mbx2aYN",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "kkmj_iY16x4A",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 0,
    "displayOrderCalendar": 999,
    "dueDate": 1460267940,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Essay",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "o28X",
    "visibleDate": null,
    "weight": 2
  },
  {
    "id": "USdayEofQCij",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "HtDR6F49kP3X",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 0,
    "displayOrderCalendar": 999,
    "dueDate": 1460181540,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Overall Podcast Videos Grade (for details, see Custom Reporting Tool)",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 14,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "QBuS",
    "visibleDate": null,
    "weight": 7
  },
  {
    "id": "_UhQL3N8MJdZ",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "4nZm5_6MPu3K",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 0,
    "displayOrderCalendar": 999,
    "dueDate": 1460181540,
    "extraCredit": true,
    "graded": true,
    "gradingScale": "g9DC0hkjf39-",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Overall Extra Credit (computed at end of semester)",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 6,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "5Une",
    "visibleDate": null,
    "weight": 6
  },
  {
    "id": "bWU7pEz9x_Ny",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "MHDwlFKDHEaA",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 5,
    "displayOrderCalendar": 999,
    "dueDate": 1456037940,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#6 Team Deliverable: Test Plan and Specification",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "bMuA",
    "visibleDate": null,
    "weight": 2
  },
  {
    "id": "bg3DWjq3A6Rb",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "HtDR6F49kP3X",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 1,
    "displayOrderCalendar": 999,
    "dueDate": 1460181540,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Overall Podcast Readings Grade (for details, see Custom Reporting Tool)",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 900,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "kew3",
    "visibleDate": null,
    "weight": 3.6
  },
  {
    "id": "kc5tnhze702K",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "DI7NMahzVk2X",
    "courseID": "5wyigGxZA8uJ",
    "description": "<p>Course attendance grade.</p>\n",
    "displayOrder": 0,
    "displayOrderCalendar": 999,
    "dueDate": 1460181540,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Overall Course Attendance Grade",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "Ly8I",
    "visibleDate": null,
    "weight": 100
  },
  {
    "id": "mHJQM77Xw5GD",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "MHDwlFKDHEaA",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 2,
    "displayOrderCalendar": 999,
    "dueDate": 1454223540,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#3 Team Deliverable: Requirements Document",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "yLEn",
    "visibleDate": null,
    "weight": 2
  },
  {
    "id": "mQfRyYKPmfoc",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "MHDwlFKDHEaA",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 7,
    "displayOrderCalendar": 999,
    "dueDate": 1460008740,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#8 Team Deliverable: Video Report of Project",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "TTr7",
    "visibleDate": null,
    "weight": 2
  },
  {
    "id": "tKeP8a-gxpnJ",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "MHDwlFKDHEaA",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 3,
    "displayOrderCalendar": 999,
    "dueDate": 1454828340,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#4 Team Deliverable: Pert & Gantt Charts",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "WCHU",
    "visibleDate": null,
    "weight": 2
  },
  {
    "id": "tYniptys8XWh",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "MHDwlFKDHEaA",
    "courseID": "5wyigGxZA8uJ",
    "description": "",
    "displayOrder": 4,
    "displayOrderCalendar": 999,
    "dueDate": 1455433140,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#5 Team Deliverable: Design Document",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "CZF_",
    "visibleDate": null,
    "weight": 2
  },
  {
    "id": "td3IU91giAVP",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": null,
    "categoryID": "T0LTPISJ6ZgW",
    "courseID": "5wyigGxZA8uJ",
    "description": "<p>Grade for reading The Five Orders of Ignorance.</p>\n",
    "displayOrder": 0,
    "displayOrderCalendar": 999,
    "dueDate": 1452726000,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Read Orders of Ignorance",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "assignment",
    "typeID": "",
    "url": "dAZn",
    "visibleDate": null,
    "weight": 0.4
  },
  {
    "id": "-IWjqkSoWBfq",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1451890800,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Project report for week 1.",
    "displayOrder": 0,
    "displayOrderCalendar": 999,
    "dueDate": 1452726000,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#1 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 10,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": 1451890800,
    "type": "Exam",
    "typeID": "FkNsQ25clfEI",
    "url": "zSAK",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "3d3yon3K390E",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 5,
    "displayOrderCalendar": 999,
    "dueDate": 1455433140,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#6 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "Exam",
    "typeID": "UAE2sqvtmvZ_",
    "url": "EiUs",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "4N-sjTq5GSwd",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 8,
    "displayOrderCalendar": 999,
    "dueDate": 1457247540,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#9 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "Exam",
    "typeID": "r32_jftmlYjR",
    "url": "RsYP",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "4PAIWxs_XO29",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 2,
    "displayOrderCalendar": 999,
    "dueDate": 1454223540,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#3 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "Exam",
    "typeID": "9ca3qqm27uPE",
    "url": "jx2t",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "5Mdq5BpkxaXN",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 9,
    "displayOrderCalendar": 999,
    "dueDate": 1457852340,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#10 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "Exam",
    "typeID": "od9mSYRIGQ2_",
    "url": "O77E",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "Fe641bnHWd8p",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 4,
    "displayOrderCalendar": 999,
    "dueDate": 1454828340,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#5 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "Exam",
    "typeID": "cXo4PGSwc7r5",
    "url": "z8fS",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "IuIyc7z3Rmoz",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 7,
    "displayOrderCalendar": 999,
    "dueDate": 1456642740,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#8 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": 1515394800,
    "type": "Exam",
    "typeID": "QF4AFY8ii07N",
    "url": "b6nv",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "P1gsflHKAfK_",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 10,
    "displayOrderCalendar": 999,
    "dueDate": 1458453540,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#11 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "Exam",
    "typeID": "2uvyPq3IWZUn",
    "url": "DS4g",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "VKMSpZWCXhhJ",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 6,
    "displayOrderCalendar": 999,
    "dueDate": 1456037940,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#7 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": 1515394800,
    "type": "Exam",
    "typeID": "gSOr25zSbFub",
    "url": "GZ6r",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "XgFSfQbRbj1E",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 13,
    "displayOrderCalendar": 999,
    "dueDate": 1460267940,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#14 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "Exam",
    "typeID": "S2GmEo5HQgyc",
    "url": "PXzo",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "_wT87tRsoZKB",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 3,
    "displayOrderCalendar": 999,
    "dueDate": 1454223540,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#4 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "Exam",
    "typeID": "Rky0KOfNCkWn",
    "url": "nA0p",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "jaZxqj2fpGel",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 11,
    "displayOrderCalendar": 999,
    "dueDate": 1459058340,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#12 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "Exam",
    "typeID": "gj89o2jsDXWw",
    "url": "Mf75",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "k4smTZtzFriJ",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 2,
    "displayOrderCalendar": 999,
    "dueDate": 1453618740,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#3 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": 0,
    "type": "Exam",
    "typeID": "qWD7eXb9c5EH",
    "url": "i5Jr",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "pt-GCSxr1VaK",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 12,
    "displayOrderCalendar": 999,
    "dueDate": 1459663140,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#13 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "Exam",
    "typeID": "1jXInEd0-958",
    "url": "125B",
    "visibleDate": null,
    "weight": 1.5
  },
  {
    "id": "sBcyjGCYr4C0",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1452495600,
    "categoryID": "b7zt9jxXPRLu",
    "courseID": "5wyigGxZA8uJ",
    "description": "Weekly report on project work.",
    "displayOrder": 1,
    "displayOrderCalendar": 999,
    "dueDate": 1453013940,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "hyEV20JZBdqI",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#2 Project Report",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 0,
    "points": 8,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": 1452495600,
    "type": "Exam",
    "typeID": "ybhJzLkCjXFu",
    "url": "okzi",
    "visibleDate": 1451890800,
    "weight": 1.5
  },
  {
    "id": "MHCF3raG605R",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1456930800,
    "categoryID": "WEqh0tGDeaCR",
    "courseID": "5wyigGxZA8uJ",
    "description": "Midterm",
    "displayOrder": 0,
    "displayOrderCalendar": 999,
    "dueDate": 1456974000,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Midterm",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "ExamOther",
    "typeID": "",
    "url": "PKaf",
    "visibleDate": null,
    "weight": 17
  },
  {
    "id": "OitaxLEHuv0i",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1457765940,
    "categoryID": "MHDwlFKDHEaA",
    "courseID": "5wyigGxZA8uJ",
    "description": "Report completion of code review.",
    "displayOrder": 6,
    "displayOrderCalendar": 999,
    "dueDate": 1458453540,
    "extraCredit": false,
    "graded": true,
    "gradingScale": "g9DC0hkjf39-",
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "#7 Team Deliverable: Code Review Performed",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": 1458453540,
    "type": "Exam",
    "typeID": "GWMIvlHAefZt",
    "url": "aR_D",
    "visibleDate": 1457852340,
    "weight": 2
  },
  {
    "id": "RbelprM5VycJ",
    "allowLateSubmission": false,
    "allowScoreDrop": true,
    "beginDate": 1460494800,
    "categoryID": "zWhmWArcY4JR",
    "courseID": "5wyigGxZA8uJ",
    "description": "Final\n",
    "displayOrder": 0,
    "displayOrderCalendar": 999,
    "dueDate": 1460505600,
    "extraCredit": false,
    "graded": true,
    "gradingScale": null,
    "includeScoreInFinalGrade": true,
    "minScore": 0,
    "name": "Final",
    "onlineSubmission": "none",
    "passScoreRequired": false,
    "passingScore": 70,
    "points": 100,
    "rubric": null,
    "scoreEntry": "points",
    "scoreVisibleDate": null,
    "type": "ExamOther",
    "typeID": "",
    "url": "HL2j",
    "visibleDate": null,
    "weight": 17
  }
]